CREATE DATABASE IF NOT EXISTS GameData;
USE GameData;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    score INTEGER(10) NOT NULL
);

SELECT * FROM users;